### ISSUE TITLE
getting betas

### ISSUE THREAD

**Issue by billgreenwald** [StoreyLab/gcatest#1]
Hi!

I am thinking of using GCA in some work I am starting soon, and am wondering if it is possible to get association betas and/or SE's for the betas from this package?  If not, do you have a recommended workflow for getting betas (such as just regressing the significant SNPs from gcat against the phenotype)?  

Thanks!

**Comment by whao89** [comment]
You can easily replicate the test without using the package in the following way. Supposing `X` is your genotype matrix (snps by individuals), `LF` is the matrix of logistic factors outputted by the `lfa` package, and `trait` is a vector for your trait, the following should work...

```
out <- lapply(1:nrow(X), function(i){ glm(cbind(X[i,], 2-X[i,]) ~ -1 + LF + trait, family=binomial()) })
```

Each element in the list `out` will be the typical output for a `glm()` call in R and has all the information you want. Note that this will be a lot slower but not prohibitively. 

Hope this helps! I'll add something to the package to handle this when I get a chance. Let me know if you need anything else.

**Comment by billgreenwald** [comment]
Thanks!  I have another separate question; please separate it into a different issue thread if you would like.

When I run the check for SNPs that violate the null model to pick how many latent factors I should use, I sometimes get the error (on a very small set of test data):

Error: denom != 0 is not TRUE.

However, running the same data multiple times will eventually run it fine without this error.  Is this an error I should be wary of, or should I just repeat the process until it runs fine without the error?  Additionally, running it multiple times produces different filter results, ranging from filtering 0 of my 468 variants, to half of my 468 variants.

My exact code, for reference, is:

```
nlf=3
LFs=lfa(genotypeMatrix,nlf) #3 is chosen from the example
gof = model.gof(genotypeMatrix, LFs, B=nlf-1) 
```

**Comment by whao89** [comment]
Let's move this to email since this will probably get pretty specific to your dataset/case.
